from PySide6.QtWidgets import QWidget, QHBoxLayout, QLabel, QGroupBox

class CompliancePanel(QGroupBox):
    def __init__(self, parent=None):
        super().__init__("Painel de Conformidade Ambiental", parent)
        self.layout = QHBoxLayout(self)
        
        self.lbl_licenses = self._create_indicator("Licenças: --")
        self.lbl_docs = self._create_indicator("Documentação: --")
        self.lbl_cond = self._create_indicator("Condicionantes: --")
        
    def _create_indicator(self, text: str):
        lbl = QLabel(text)
        lbl.setStyleSheet("padding: 10px; border-radius: 5px; background-color: #E0E0E0; color: black; font-weight: bold;")
        self.layout.addWidget(lbl)
        return lbl
        
    def update_snapshot(self, snapshot: dict):
        """Updates UI based on snapshot generated by ComplianceService."""
        lic = snapshot.get("licenses", {})
        cond = snapshot.get("conditionants", {})
        
        self._apply_style(self.lbl_licenses, f"Licenças: {lic.get('message', '')}", lic.get("status", "gray"))
        self._apply_style(self.lbl_cond, f"Condicionantes: {cond.get('message', '')}", cond.get("status", "gray"))
        self._apply_style(self.lbl_docs, "Documentos: Validação Pendente", "yellow")
        
    def _apply_style(self, lbl: QLabel, text: str, status: str):
        lbl.setText(text)
        color = "#E0E0E0"
        if status == "green": color = "#A5D6A7"
        elif status == "yellow": color = "#FFF59D"
        elif status == "red": color = "#EF9A9A"
        lbl.setStyleSheet(f"padding: 10px; border-radius: 5px; background-color: {color}; color: black; font-weight: bold;")
