from typing import Dict, Any, Callable
from pathlib import Path
from .base import BaseComparator
from .utils import compare_sources, load_input, write_result

class SHPMetricaComparator(BaseComparator):
    name = "SHP x Métrica"
    
    def validate(self, context: Dict[str, Any]) -> bool:
        inputs = context.get("inputs", {})
        return "SHP" in inputs and "MT" in inputs
        
    def execute(self, inputs: Dict[str, Path], output_dir: Path, progress_callback: Callable[[int, str], None] = None) -> Dict[str, Any]:
        if progress_callback:
            progress_callback(10, "Carregando arquivos...")
            
        data = {
            "SHP": load_input("SHP", inputs["SHP"]),
            "MT": load_input("MT", inputs["MT"])
        }
        
        if progress_callback:
            progress_callback(50, "Comparando dados...")
            
        sheets = compare_sources(data["SHP"], data["MT"], "SHP", "MT", ("area",), "MT")
        
        if progress_callback:
            progress_callback(80, "Gerando relatório...")
            
        output_file = output_dir / "Comparativo_SHPxMetrica.xlsx"
        write_result(output_file, sheets)
        
        discrepancies = len(sheets.get("Somente_SHP", [])) + len(sheets.get("Somente_MT", [])) + sum(1 for row in sheets.get("Comparacao", []) if row.get("Status") != "OK")
        
        if progress_callback:
            progress_callback(100, "Concluído.")
            
        return {
            "output_file": str(output_file),
            "summary": {
                "shp_records": len(data["SHP"]),
                "mt_records": len(data["MT"]),
                "compared": len(sheets.get("Comparacao", []))
            },
            "discrepancies": discrepancies
        }
        
    def generate_report(self, result: Dict[str, Any]) -> str:
        # Report is already generated by utils.write_result. 
        # This can be used for extra formats like PDF/CSV in the future.
        return result.get("output_file", "")
